---

- hosts: localhost
  connection: local
  gather_facts: true

  tasks:

      - name: create sites-enabled folder in the nginx
        file:
          path: '{{ item }}'
          recurse: yes
          state: directory
          owner: root
          group: root
          mode: 0775
        with_items:
          - /etc/ssl/private
          - /etc/nginx/sites-enabled

      - name: Copy the relevant nginx certificate files to its specific certificate directories
        copy:
          src: '{{ item.src }}'
          dest: '{{ item.dest }}'
          owner: root
          group: root
        with_items:
          - { src: /home/vagrant/vibrato-code-test/docker-repo/jenkins/Utilities/certificates/jenkins-selfsigned.key, dest: /etc/ssl/private/ }
          - { src: /home/vagrant/vibrato-code-test/docker-repo/jenkins/Utilities/certificates/jenkins-selfsigned.crt, dest: /etc/ssl/certs/ }
          - { src: /home/vagrant/vibrato-code-test/docker-repo/jenkins/Utilities/certificates/dhparam.pem, dest: /etc/ssl/certs/ }
          - { src: /home/vagrant/vibrato-code-test/docker-repo/jenkins/Utilities/scripts/jenkins.conf , dest: /etc/nginx/sites-enabled/default }
          - { src: /home/vagrant/vibrato-code-test/docker-repo/jenkins/Utilities/scripts/nginx.conf , dest: /etc/nginx/nginx.conf }
          - { src: /home/vagrant/vibrato-code-test/docker-repo/jenkins/Utilities/scripts/ssl.conf , dest: /etc/nginx/conf.d/ssl.conf }

      - name: restart the nginx service
        service: name=nginx state=restarted
        register: nginx_status

      - debug: var='{{ nginx_status }}'
